config/routes.rb
Rails.application.routes.draw do
root 'pages#home'
  devise_for :users,
    path: '',
    path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
    controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
  resources :items, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  resources :renter_reviews, only: [:create, :destroy]
  resources :owner_reviews, only: [:create, :destroy]

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  get 'search' => 'pages#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

  validates :fullname, presence: true, length: {maximum: 50}

  has_many :items
  has_many :reservations

  has_many :renter_reviews, class_name: "RenterReview", foreign_key: "renter_id"
  has_many :owner_reviews, class_name: "OwnerReview", foreign_key: "owner_id"

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first

    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.fullname = auth.info.name   # assuming the user model has a name
        user.image = auth.info.image # assuming the user model has an image
        # If you are using confirmable and the provider(s) you use validate emails,
        # uncomment the line below to skip the confirmation emails.
        user.uid = auth.uid
        user.provider = auth.provider
        user.skip_confirmation!
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:fullname, :phone_number, :description])
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @items = Item.where(active: true).limit(3)
    # STEP 1
    if params[:search].present? && params[:search].strip != ""
      session[:loc_search] = params[:search]
    end

    # STEP 2
    if session[:loc_search] && session[:loc_search] != ""
      @items_address = Item.where(active: true).near(session[:loc_search], 5, order: 'distance')
    else
      @items_address = Item.where(active: true).all
    end

    # STEP 3
    @search = @items_address.ransack(params[:q])
    @items = @search.result

    @arritems = @items.to_a

    # STEP 4
    if (params[:start_date] && params[:end_date] && !params[:start_date].empty? &&  !params[:end_date].empty?)

      start_date = Date.parse(params[:start_date])
      end_date = Date.parse(params[:end_date])

      @items.each do |item|

        not_available = item.reservations.where(
          "(? <= start_date AND start_date <= ?)
          OR (? <= end_date AND end_date <= ?)
          OR (start_date < ? AND ? < end_date)",
          start_date, end_date,
          start_date, end_date,
          start_date, end_date
        ).limit(1)

        if not_available.length > 0
          @arritems.delete(item)
        end
      end
    end

  end

  def search
    # STEP 1
    if params[:search].present? && params[:search].strip != ""
      session[:loc_search] = params[:search]
    end

    # STEP 2
    if session[:loc_search] && session[:loc_search] != ""
      @items_address = Item.where(active: true).near(session[:loc_search], 5, order: 'distance')
    else
      @items_address = Item.where(active: true).all
    end

    # STEP 3
    @search = @items_address.ransack(params[:q])
    @items = @search.result

    @arritems = @items.to_a

    # STEP 4
    if (params[:start_date] && params[:end_date] && !params[:start_date].empty? &&  !params[:end_date].empty?)

      start_date = Date.parse(params[:start_date])
      end_date = Date.parse(params[:end_date])

      @items.each do |item|

        not_available = item.reservations.where(
          "(? <= start_date AND start_date <= ?)
          OR (? <= end_date AND end_date <= ?)
          OR (start_date < ? AND ? < end_date)",
          start_date, end_date,
          start_date, end_date,
          start_date, end_date
        ).limit(1)

        if not_available.length > 0
          @arritems.delete(item)
        end
      end
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)

      if user.image
        "http://graph.facebook.com/#{user.uid}/picture?type=large"
      else
        gravatar_id = Digest::MD5::hexdigest(user.email).downcase
        "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identical&s=150"
      end

  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KiWiKsport</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD0Zq--tOosdf3Z5EhMEa0elNb9sM5_quI&libraries=places"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/hot-sneaks/jquery-ui.css">
  </head>
  <body class= "menuspace">
    <%= render 'shared/navbar' %>
    <%= render 'shared/message' %>




    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/home.html.erb
<div class="row">
  <div class="col-md-7 banner">
    <h1>Avec <span class="text-red">KiWiKsport</span>, être actif est plus facile que jamais.</h1>
  </div>
</div>

<%= search_form_for @search, url: search_path do |f| %>
  <div class="row">
    <div class="col-md-3">
      <div class="form-group select">
        <%= f.select :categorie_eq, [["Soccer", "Soccer"], ["Vélo", "Vélo"], ["Camping", "Camping"], ["Kayak", "Kayak"]],
                      id: "categorie", prompt: "Choisissez...", class: "form-control" %>
      </div>
    </div>
    <div class="col-md-3">
      <%= text_field_tag :search, params[:search], placeholder: "Where are you going?", class: "form-control", id: "autolocation" %>
    </div>
    <div class="col-md-3">
      <%= text_field_tag :start_date, params[:start_date], placeholder: "Start Date", class: "form-control datepicker" %>
    </div>
    <div class="col-md-3">
      <%= text_field_tag :end_date, params[:end_date], placeholder: "End Date", class: "form-control datepicker" %>
    </div>
  </div>
  <br/><br/>

  <div class="row">
    <div class="col-md-offset-4 col-md-4">
      <%= submit_tag "Chercher", class: "btn btn-normal btn-block" %>
    </div>
  </div>
<% end %>

<br/><hr/><br/>

<!-- HOMES -->
<div><h3>Items</h3></div>
<br/>

<div class="row">
  <%= render partial: "items/items_list", locals: {items: @items} %>
</div>

<!-- CITIES -->
<div><h3>Catégories</h3></div>
<br/>

<div class="row">
  <div class="col-md-3 col-sm-12">
    <a href="http://localhost:3000/search?utf8=%E2%9C%93&q%5Bcategorie_eq%5D=Soccer&search=&start_date=&end_date=&commit=Search">
      <div class="discovery-card" style="background-image: url('/assets/blank.jpg')"></div>
    </a>
  </div>
  <div class="col-md-3 col-sm-12">
    <a href="http://localhost:3000/search?utf8=%E2%9C%93&search=london">
      <div class="discovery-card" style="background-image: url('/assets/blank.jpg')"></div>
    </a>
  </div>
  <div class="col-md-3 col-sm-12">
    <a href="http://localhost:3000/search?utf8=%E2%9C%93&search=paris">
      <div class="discovery-card" style="background-image: url('/assets/blank.jpg')"></div>
    </a>
  </div>
  <div class="col-md-3 col-sm-12">
    <a href="http://localhost:3000/search?utf8=%E2%9C%93&search=miami">
      <div class="discovery-card" style="background-image: url('/assets/blank.jpg')"></div>
    </a>
  </div>
</div>


<script>
  $('#start_date').datepicker({
    dateFormat: 'dd-mm-yy',
    minDate: 0,
    maxDate: '3m',
    onSelect: function(selected) {
      $('#end_date').datepicker("option", "minDate", selected);
      $('#end_date').attr("disabled", false);
    }
  });

  $('#end_date').datepicker({
    dateFormat: 'dd-mm-yy',
    minDate: 0,
    maxDate: '3m',
    onSelect: function(selected) {
      $('#start_date').datepicker("option", "maxDate", selected);
    }
  });

  $(function() {
    $("#autolocation").geocomplete();
  })
</script>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
      toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "KiWiKsport", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <%= form_tag search_path, class: "navbar-form navbar-left", method: :get do %>
          <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Anywhere", class: "form-control" %>
          </div>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
        <li>
          <button class="btn btn-form btn-small">
            <%= link_to "publiez votre annonce", new_item_path, style: "color: white; text-decoration: none;" %>
          </button>
        </li>

        <% if (!user_signed_in?) %>
          <li><%= link_to "Se Connecter", new_user_session_path %></li>
          <li><%= link_to "S'inscrire", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle"
              data-toggle="dropdown" role="button"
              aria-haspopup="true"
              aria-expanded="false">
              <%= image_tag avatar_url(current_user), class: "img-circle avatar-medium" %> &nbsp;
              <%= current_user.fullname %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Gérez vos annonces", items_path %></li>
                <li><%= link_to "Annoncez votre article", new_item_path %></li>
                <li><%= link_to "Vos réservations", your_reservations_path %></li>

              <li role="separator" class="divider"></li>
              <li><%= link_to "Modifier le profil", edit_user_registration_path %></li>
              <li><%= link_to "Se Déconnecter", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>